name: daydreams

services:
  chroma:
    image: chromadb/chroma:0.6.3
    container_name: ${COMPOSE_PROJECT_NAME}_chroma
    restart: always
    ports:
      - "8000:8000"
  mongo:
    image: mongo:8.0.4
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: ${COMPOSE_PROJECT_NAME}_mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:
